# Generated by Django 4.1.5 on 2023-01-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of menu item', max_length=255)),
                ('url', models.CharField(default='menu/', max_length=255)),
                ('is_root', models.BooleanField(default=True)),
                ('children', models.ManyToManyField(null=True, to='my_menu.menu')),
            ],
        ),
    ]
