# Generated by Django 4.1.5 on 2023-01-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='children',
            field=models.ManyToManyField(blank=True, null=True, to='my_menu.menu'),
        ),
    ]
